FROM aps-runtime-base-jdk11

# We already inherit everything else we need to run, so we only need to add our webb app.
COPY target/aps-webtemplate-gui-service-1.0.0.jar /aps-platform/bundles/

# Dont! This will run immediately on creation!
#RUN /aps-platform/bin/run.sh
